info:
  contact: {}
paths:
  /getAllData:
    get:
      consumes:
      - application/json
      description: Retrieves all predefined data assets from the ledger
      produces:
      - application/json
      responses:
        "200":
          description: All Data Retrieved
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Error occurred
          schema:
            type: string
      summary: Get all predefined data assets
      tags:
      - assets
  /getTxnHistory:
    get:
      consumes:
      - application/json
      description: Retrieves the transaction history for a specific ledger entry by
        ID
      parameters:
      - description: ID of the Data to retrieve history for
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Transaction History Retrieved
          schema:
            items:
              additionalProperties: true
              type: object
            type: array
        "400":
          description: Error occurred
          schema:
            type: string
      summary: Get transaction history for a specific ID
      tags:
      - history
  /readData:
    get:
      consumes:
      - application/json
      description: Retrieves specific data from the ledger by ID
      parameters:
      - description: ID of the Data to retrieve
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Data Retrieved
          schema:
            type: object
        "400":
          description: Error occurred
          schema:
            type: string
      summary: Read specific data from the ledger
      tags:
      - data
  /respond:
    post:
      consumes:
      - application/json
      description: Update or create a response in the ledger by its ID
      parameters:
      - description: ID of the Response
        in: formData
        name: id
        required: true
        type: string
      - description: Subscribed Content as a JSON string
        in: formData
        name: subscribedContent
        required: true
        type: string
      - description: Published Content as a JSON string
        in: formData
        name: publishedContent
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Response Updated
          schema:
            type: string
        "400":
          description: Error occurred
          schema:
            type: string
      summary: Respond to a message on the ledger
      tags:
      - responses
  /update:
    post:
      consumes:
      - application/json
      description: Update or add a message by its ID
      parameters:
      - description: ID of the Message
        in: formData
        name: id
        required: true
        type: string
      - description: Type of the Message (Standard or Corrective)
        in: formData
        name: messageType
        required: true
        type: string
      - description: Content of the Message as a JSON string
        in: formData
        name: messageContent
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Message Updated
          schema:
            type: string
        "400":
          description: Error occurred
          schema:
            type: string
      summary: Update a message on the ledger
      tags:
      - messages
  /validateMessage:
    post:
      consumes:
      - application/json
      description: Compares the subscribed content with the message content in the
        world state
      parameters:
      - description: ID of the Message to validate
        in: formData
        name: messageID
        required: true
        type: string
      - description: Subscribed Content as a JSON string
        in: formData
        name: subscribedContent
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Validation Result
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Error occurred
          schema:
            type: string
      summary: Validate a message in the ledger
      tags:
      - validation
swagger: "2.0"
